version: '3'
services:
  web:
    image: romanfern/node-web-app
    build: .
    ports:
      - "49160:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=mongouser
      - MONGO_PASSWORD=mongopassword
      - MONGO_DATABASE=nodeapp
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
      - MONGO_INITDB_DATABASE=nodeapp
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: